feat: controller, service 수정 #14
hook-killer/back-end pull request #19
Opened 2023-10-10 01:43 UTC by kwchoi11

controller, service 수정했습니다. 
NoticeService 파일에서 saveNotice 부분의 빌더는 리뷰 받고 채워서 다시 올리겠습니다.

2023-10-10 03:33 UTC, bongsh0112 requested changes
고생하셨습니다
수정사항 확인해주세요

2023-10-10 03:33 UTC, bongsh0112 commented on src/main/java/HookKiller/server/notice/controller/NoticeController.java
> +    public NoticeArticleDto getNoticeArticle(@PathVariable Long noticeArticleId, HttpServletRequest request, LanguageType languageType) {
Controller에서 LanguageType을 받을 수 있을 지가 확실하지않네요
아마 `requestHeader`에 넣어주고 받을 것 같습니다
이미 밑에서 해준 것 같으니 `LanguageType`을 빼도 될 것 같아요
또 `requestHeader`를 사용하기 위해서는 `@RequestHeader` 어노테이션에 대해서도 알아보시면 좋을 것 같네요

2023-10-10 03:33 UTC, bongsh0112 commented on src/main/java/HookKiller/server/notice/controller/NoticeController.java
> +    public List<NoticeArticleDto> getNoticeArticleList(HttpServletRequest request, LanguageType languageType, NoticeArticleDto requestData) {
마찬가지로 `LanguageType`은 `requestHeader`에서 뽑아올 수 있도록 구성할 것이므로 빼도 될 것 같습니다

2023-10-10 03:33 UTC, bongsh0112 commented on src/main/java/HookKiller/server/notice/controller/NoticeController.java
> +    public void addNotice(@RequestBody @Valid NoticeArticleDto articleRequest, NoticeContentDto contentRequest) {
`@Valid`를 사용하려면 DTO 내에서 작업이 필요합니다
[참고](https://github.com/hook-killer/back-end/pull/18/files#diff-d6356f6eb471231b0b605bc195828754c9e599a6956a7c51841dc740d56f01c9)해보세요

2023-10-10 03:33 UTC, bongsh0112 commented on src/main/java/HookKiller/server/notice/controller/NoticeController.java
> +                             @RequestBody @Valid NoticeArticleDto articleDto, NoticeContentDto contentDto) {
마찬가지로 `@Valid`를 사용하기 위해서는 따로 작업이 필요합니다
`@RequestBody`를 사용할 때는
`@RequestBody @Valid UpdateNoticeRequest body`와 같이 구성하고
request dto를 하나 만들어보시는게 나을 수도 있겠네요

2023-10-10 03:33 UTC, bongsh0112 commented on src/main/java/HookKiller/server/notice/controller/NoticeController.java
> +    }
`@DeleteMapping`에 대해서는 추가적으로 찾아보셔야 할 것 같네요

2023-10-10 03:33 UTC, bongsh0112 commented on src/main/java/HookKiller/server/notice/dto/NoticeArticleDto.java
> +public class NoticeArticleDto {
dev을 머지하시고
`AbstractTimestamp`를 상속받아보세요

2023-10-10 03:33 UTC, bongsh0112 commented on src/main/java/HookKiller/server/notice/dto/NoticeContentDto.java
> +    }
`of` 메소드로 build하기 좋습니다

2023-10-10 03:33 UTC, bongsh0112 commented on src/main/java/HookKiller/server/notice/exception/NoticeException.java
> +    NOTICE_ARTICLE_NOT_FOUND_EXCEPTION(NOT_FOUND.value(), "404-1", "공지사항 게시물이 존재하지 않습니다.");
굿굿 좋습니다
앞으로 notice와 관련된 Exception들은 모두 여기에 모아놓으면 되겠네요

2023-10-10 03:33 UTC, bongsh0112 commented on src/main/java/HookKiller/server/repository/NoticeArticleRepository.java
> +    NoticeArticle getById(Long id);
레포지토리에서 `getById`는 쓰지 않는 것이 좋겠네요
아마 `findById`라는 메소드가 기본적으로 제공되는 것으로 알고 있습니다

2023-10-10 03:33 UTC, bongsh0112 commented on src/main/java/HookKiller/server/service/NoticeService.java
> +    @Transactional(readOnly = true)
readonly 좋습니다

2023-10-10 03:33 UTC, bongsh0112 commented on src/main/java/HookKiller/server/service/NoticeService.java
> +        }
`stream`을 써보는 것은 어떨까요

2023-10-10 03:33 UTC, bongsh0112 commented on src/main/java/HookKiller/server/service/NoticeService.java
> +    }
이 코드는 나중에 또 쓸 수 있으니
`NoticeContentDto`에 `from` 메소드를 만들어보는 것은 어떨까요?
```suggestion
    public NoticeContentDto getNotice(Long id) {
        NoticeContent noticeContent = noticeContentRepository.findById(id).orElseThrow(() -> NoticeArticleNotFoundException.EXCEPTION);

        return NoticeContentDto.from(noticeContent);
    }
```
처럼 나오도록 한번 만들어보세요!

2023-10-10 03:33 UTC, bongsh0112 commented on src/main/java/HookKiller/server/service/NoticeService.java
> +    }
JPA에서 `update`는 어떻게 하는지 리서치해보시는것도 추천드립니다

2023-10-10 03:33 UTC, bongsh0112 commented on src/main/java/HookKiller/server/service/NoticeService.java
> +    }
이런 것들을 서비스에서 따로 정의하는것도 괜찮지만,
JPA repository에서 바로 가져올 수도 있을 것 같네요.

2023-10-10 06:57 UTC, kwchoi11 commented on src/main/java/HookKiller/server/service/NoticeService.java
> +    }
그러면 서비스에서 이것들은 지워버리고 컨트롤러에서 바로 가져오도록 하면 되나요?

2023-10-12 00:47 UTC, donsonioc2010 commented on src/main/java/HookKiller/server/config/security/SecurityConfig.java
> +                                            "/register", "/health", "/notice/**").permitAll()
해당 코드는 테스트케이스에서만 사용해주시고, 롤백해주시기 바랍니다.

2023-10-12 00:47 UTC, donsonioc2010 commented on src/main/java/HookKiller/server/common/type/LanguageType.java
> +    }
Default로 KO를 주기를 의도한 것 같은데, 실제 Value가 들어온 경우 (ex: "abc")에는 Exception이 발생하나요 아니면 KO가 반환되나요?

2023-10-12 00:47 UTC, donsonioc2010 commented on src/main/java/HookKiller/server/common/type/LanguageType.java
> +        if(request == null)
위에서 Default로 KO를 주기로 생각한것 같은데 request가 null인 경우에는 return을 EXCEPTION으로 할 예정인 건가요???

2023-10-13 05:09 UTC, kwchoi11 commented
공지사항에 페이지네이션과 파파고 적용하면 완료될 것 같습니다.

2023-10-13 09:18 UTC, donsonioc2010 approved these changes
넴

2023-10-13 09:31 UTC, bongsh0112 approved these changes

2023-10-13 09:47 UTC, merged