Feat/10 board - 게시판 entity , repo 작성
hook-killer/back-end pull request #20
Opened 2023-10-10 01:46 UTC by lgsok00

게시판 entity, repo 작성 완료했습니다.

2023-10-10 02:17 UTC, bongsh0112 requested changes
고생하셨습니다
수정사항 확인해주세요

2023-10-10 02:17 UTC, bongsh0112 commented on src/main/java/HookKiller/server/board/controller/ArticleController.java
> +  @GetMapping("{/boardId}")
`@GetMapping("/{boardId}")`
가 맞지 않을까요..?

2023-10-10 02:17 UTC, bongsh0112 commented on src/main/java/HookKiller/server/board/entity/Article.java
> +    private Long updatedUser;
create 혹은 update한 User의 Id를 쓰는거면
`createdUserId`와 같은 방식으로 쓰는게 좋겠네요

2023-10-10 02:17 UTC, bongsh0112 commented on src/main/java/HookKiller/server/board/entity/Article.java
> +    private int likeCount;
혹시 likeCount 업데이트는 어떻게 진행되나요?
좋아요 누르면 이 값이 업데이트 되어야 할텐데요

2023-10-10 02:17 UTC, bongsh0112 commented on src/main/java/HookKiller/server/board/service/BoardService.java
> +        return boardDtoList;
우선 빈 리스트만 리턴하도록 해놓은 것 맞나요

2023-10-10 02:17 UTC, bongsh0112 commented on src/main/java/HookKiller/server/board/service/ArticleService.java
> +  }
주석에 따라 혼자서 다시 작성해보세요

2023-10-10 02:17 UTC, bongsh0112 commented on src/main/java/HookKiller/server/board/repository/ArticleContentRepository.java
> +  public Optional<ArticleContent> findByArticleAndLanguage(Article article, String language);
Optional로 리턴한다면
나중에 Exception을 만들어서 핸들링 해주어야 합니다
Exception도 살펴보세요

2023-10-10 02:17 UTC, bongsh0112 commented on src/main/java/HookKiller/server/board/entity/Reply.java
> +    private Article article;
`@ManyToOne` 좋습니다

2023-10-10 02:17 UTC, bongsh0112 commented on src/main/java/HookKiller/server/board/entity/ReplyContent.java
> +    private Reply reply;
`@ManyToOne` 좋습니다

2023-10-10 02:17 UTC, bongsh0112 commented on src/main/java/HookKiller/server/board/entity/Article.java
> +    @OneToMany
`@OneToMany(mappedBy = ~~~)`에 대해
공부해보시고 수정 바랍니다

2023-10-10 02:17 UTC, bongsh0112 commented on src/main/java/HookKiller/server/board/entity/Article.java
> +    @OneToMany
`@OneToMany(mappedBy = ~~~)`에 대해
공부해보시고 수정 바랍니다

2023-10-10 02:17 UTC, bongsh0112 commented on src/main/java/HookKiller/server/board/entity/Article.java
> +    @OneToMany
`@OneToMany(mappedBy = ~~~)`에 대해
공부해보시고 수정 바랍니다

2023-10-10 02:17 UTC, bongsh0112 commented on src/main/java/HookKiller/server/board/entity/ArticleContent.java
> +    private String language;
`LanguageType`이라는 이넘을 만드신 걸로 아는데
혹시 이건 어떤 필드인가요

2023-10-10 02:17 UTC, bongsh0112 commented on src/main/java/HookKiller/server/board/entity/Reply.java
> +    @OneToMany
마찬가지로 `mappedBy`를 사용해보세요

2023-10-10 05:23 UTC, donsonioc2010 requested changes
일단 바꿔오세욧

2023-10-10 05:23 UTC, donsonioc2010 commented on src/main/java/HookKiller/server/board/controller/ArticleController.java
> +  @GetMapping("{/boardId}")
맞지 `{/boardId}`는 좀 너무했다

2023-10-10 05:23 UTC, donsonioc2010 commented on src/main/java/HookKiller/server/board/controller/BoardController.java
> +import org.springframework.web.bind.annotation.*;
`import org.springframework.web.bind.annotation.*;`
는 실제 참조하는 메소드로 변경해주세요.

2023-10-10 05:23 UTC, donsonioc2010 commented on src/main/java/HookKiller/server/board/entity/Article.java
> +import jakarta.persistence.*;
`import jakarta.persistence.*`를 참조하는 메소드로 수정바람

2023-10-10 05:23 UTC, donsonioc2010 commented on src/main/java/HookKiller/server/board/entity/ArticleContent.java
> +import jakarta.persistence.*;
`import jakarta.persistence.*`를 참조하는 메소드로 수정바람

2023-10-10 05:23 UTC, donsonioc2010 commented on src/main/java/HookKiller/server/board/entity/ArticleLike.java
> +import jakarta.persistence.*;
`import jakarta.persistence.*`를 참조하는 메소드로 수정바람

2023-10-10 05:23 UTC, donsonioc2010 commented on src/main/java/HookKiller/server/board/entity/Board.java
> +import jakarta.persistence.*;
`import jakarta.persistence.*`를 참조하는 메소드로 수정바람

2023-10-10 05:23 UTC, donsonioc2010 commented on src/main/java/HookKiller/server/board/entity/Board.java
> +@Table(name = "Board")
테이블명칭만  아래와 같이 설정 바람.
```suggestion
@Table(name = "tbl_board")
```

2023-10-10 05:23 UTC, donsonioc2010 commented on src/main/java/HookKiller/server/board/entity/ArticleContent.java
> +@NoArgsConstructor(access = AccessLevel.PROTECTED)
```suggestion
@Entity
@Getter
@Table(name = "tbl_article_content")
@NoArgsConstructor(access = AccessLevel.PROTECTED)
```

2023-10-10 05:23 UTC, donsonioc2010 commented on src/main/java/HookKiller/server/board/entity/Article.java
> +public class Article extends AbstractTimeStamp {
```suggestion
@Entity
@Getter
@Table(name = "tbl_article")
@RequiredArgsConstructor
public class Article extends AbstractTimeStamp {
```

2023-10-10 05:23 UTC, donsonioc2010 commented on src/main/java/HookKiller/server/board/entity/Reply.java
> +import jakarta.persistence.*;
`import jakarta.persistence.*`를 참조하는 메소드로 수정바람

2023-10-10 05:23 UTC, donsonioc2010 commented on src/main/java/HookKiller/server/board/entity/Reply.java
> +public class Reply extends AbstractTimeStamp {
```suggestion
@Entity
@Getter
@Table(name = "tbl_reply")
@NoArgsConstructor(access = AccessLevel.PROTECTED)
public class Reply extends AbstractTimeStamp {
```

2023-10-10 05:23 UTC, donsonioc2010 commented on src/main/java/HookKiller/server/board/entity/ReplyContent.java
> +public class ReplyContent {
```suggestion
@Entity
@Getter
@Table(name = "tbl_reply_content")
@NoArgsConstructor(access = AccessLevel.PROTECTED)
public class ReplyContent {
```

2023-10-10 05:23 UTC, donsonioc2010 commented on src/main/java/HookKiller/server/board/entity/ReplyContent.java
> +import jakarta.persistence.*;
`import jakarta.persistence.*`를 참조하는 메소드로 수정바람

2023-10-10 05:23 UTC, donsonioc2010 commented on src/main/java/HookKiller/server/board/entity/ReplyContent.java
> +    private String language;
LanguageType Enum으로 해야하지 않을까?

2023-10-10 05:23 UTC, donsonioc2010 commented on src/main/java/HookKiller/server/board/exception/BaseErrorCode.java
> +
해당 클래스는 Common에 구현된 클래스 같이 쓰기바람.

2023-10-10 05:23 UTC, donsonioc2010 commented on src/main/java/HookKiller/server/board/exception/BaseException.java
> +}
해당 클래스는 Common에 구현된 클래스 같이 쓰기바람.

2023-10-10 05:23 UTC, donsonioc2010 commented on src/main/java/HookKiller/server/board/exception/ExampleException.java
> +}
이친구는 왜만든거야?

2023-10-10 05:23 UTC, donsonioc2010 commented on src/main/java/HookKiller/server/board/exception/GlobalException.java
> +public enum GlobalException implements BaseErrorCode {
BoardExceptions로 따로 뺴기 바람.  GlobalException은 이미 사용중이니..

2023-10-10 05:23 UTC, donsonioc2010 commented on src/main/java/HookKiller/server/board/repository/ArticleRepository.java
> +@Repository
필요없음.

2023-10-10 05:23 UTC, donsonioc2010 commented on src/main/java/HookKiller/server/board/repository/BoardRepository.java
> +@Repository
필요없음.

2023-10-10 05:23 UTC, donsonioc2010 commented on src/main/java/HookKiller/server/board/repository/ReplyContentRepository.java
> +@Repository
필요없음.

2023-10-10 05:23 UTC, donsonioc2010 commented on src/main/java/HookKiller/server/board/repository/ReplyRepository.java
> +@Repository
필요없음.

2023-10-12 07:22 UTC, donsonioc2010 requested changes
@lgsok00 @lljh1992 윙크

2023-10-12 07:22 UTC, donsonioc2010 commented on build.gradle
> +    implementation "org.springframework.boot:spring-boot-starter-webflux"
제거하시기 바랍니다.

2023-10-12 07:22 UTC, donsonioc2010 commented on src/main/java/HookKiller/server/board/controller/ArticleController.java
> +@RequestMapping("/articles")
이게 좀 더 어울리지 않을까요?
```suggestion
@RequestMapping("/article")
```

2023-10-12 07:22 UTC, donsonioc2010 commented on src/main/java/HookKiller/server/board/controller/ArticleController.java
> +import org.springframework.web.bind.annotation.*;
```suggestion
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

```

2023-10-12 07:22 UTC, donsonioc2010 commented on src/main/java/HookKiller/server/board/controller/ArticleController.java
> +    return articleService.getArticleList(boardId, language);
이게 낫지 않을까요?, "language"는 따로 상수화 시키는게 좋을 것 같네요.
```suggestion
    return articleService.getArticleList(boardId, BoardType.valueOf(request.getHeader("language")));
```

2023-10-12 07:22 UTC, donsonioc2010 commented on src/main/java/HookKiller/server/board/controller/ArticleController.java
> +    );
여기는 깊게 생각해봤는데 두개를 한개의 메소드에서 작업하고 Transactional 처리를 해야 할 것 같습니다.

번역에 실패하면 롤백해야 하기 떄문입니다.

2023-10-12 07:22 UTC, donsonioc2010 commented on src/main/java/HookKiller/server/board/controller/ArticleController.java
> +  @PostMapping("/{articleId}")
게시물 수정이니 아래처럼 변경하고, articleId는 PathVariable이 아닌, RequestDto에 같이 받아서 처리하는건 어떨까요?
```suggestion
  @PostMapping
```

2023-10-12 07:22 UTC, donsonioc2010 commented on src/main/java/HookKiller/server/board/controller/ArticleController.java
> +    );
여기는 깊게 생각해봤는데 두개를 한개의 메소드에서 작업하고 Transactional 처리를 해야 할 것 같습니다.

번역에 실패하면 롤백해야 하기 떄문입니다.

2023-10-12 07:22 UTC, donsonioc2010 commented on src/main/java/HookKiller/server/board/dto/ArticleRequestDto.java
> +  private Timestamp createdAt;
`AbstractTimeStamp`를 상속받으면 생성되는 컬럼인데 꼭 필요할지 의문이네요.

2023-10-12 07:22 UTC, donsonioc2010 commented on src/main/java/HookKiller/server/board/dto/ArticleRequestDto.java
> +  private Timestamp updatedAt;
`AbstractTimeStamp`를 상속받으면 생성되는 컬럼인데 꼭 필요할지 의문이네요.

2023-10-12 07:22 UTC, donsonioc2010 commented on src/main/java/HookKiller/server/board/dto/ArticleRequestDto.java
> +  }
해당 메소드는 어디서 활용중인가요?

2023-10-12 07:22 UTC, donsonioc2010 commented on src/main/java/HookKiller/server/board/dto/PostArticleRequestDto.java
> +import lombok.*;
```suggestion
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
```

2023-10-12 07:22 UTC, donsonioc2010 commented on src/main/java/HookKiller/server/board/entity/Article.java
> + */
아래의 컬럼과 동일한 정보인가요?

2023-10-12 07:22 UTC, donsonioc2010 commented on src/main/java/HookKiller/server/board/entity/Article.java
> +import jakarta.persistence.*;
```suggestion
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
```

2023-10-12 07:22 UTC, donsonioc2010 commented on src/main/java/HookKiller/server/board/entity/Article.java
> +  }
아래로 활용하면 되지 않을까요?
```suggestion
  public void updateStatus(ArticleStatus status) {
    articleStatus = status;
  }
```

2023-10-12 07:22 UTC, donsonioc2010 commented on src/main/java/HookKiller/server/board/entity/Board.java
> +import jakarta.persistence.*;
```suggestion
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
```

2023-10-12 07:22 UTC, donsonioc2010 commented on src/main/java/HookKiller/server/board/repository/ArticleContentRepository.java
> +  public Optional<ArticleContent> findByArticleAndLanguage(Article article, BoardType language);
`public`은 필요없습니다.
Interface를 학습해보시기 바랍니다.

또한 해당 메소드가 실행되는지 생각해보시기 바랍니다.

BoardType 가 왜 나오는지도 의문이네요

2023-10-12 07:22 UTC, donsonioc2010 commented on src/main/java/HookKiller/server/board/repository/ArticleRepository.java
> +  public List<Article> findAllByBoard(Board board);
public이라면 접근제어자가 굳이 필요하지 않습니다.

2023-10-12 07:22 UTC, donsonioc2010 commented on src/main/java/HookKiller/server/board/repository/ArticleRepository.java
> +  List<Article> findAllByBoardAndStatus(Board board, String status);
해당 메소드가 실행이 되는지 확인하시기 바랍니다.

또한 파라미터도 정상적으로 기입하였는지 확인바랍니다.

2023-10-12 07:22 UTC, donsonioc2010 commented on src/main/java/HookKiller/server/board/service/ArticleContentService.java
> +    articleContentRepository.saveAll(articleContentList);
ArticleController에서 했던 말처럼 articleService에서 기록했던 것처럼 한개의 메소드에서 처리가 필요할 것 같습니다.

2023-10-12 07:22 UTC, donsonioc2010 commented on src/main/java/HookKiller/server/board/service/ArticleContentService.java
> +  }
ArticleController에서 했던 말처럼 articleService에서 기록했던 것처럼 한개의 메소드에서 처리가 필요할 것 같습니다.

2023-10-12 07:22 UTC, donsonioc2010 commented on src/main/resources/application-local.yml
> +    database: js
Rollback

2023-10-13 00:29 UTC, donsonioc2010 approved these changes
LGTM

2023-10-13 00:41 UTC, bongsh0112 approved these changes
LGTM 고생하셨습니다

2023-10-13 00:41 UTC, merged